--------------------------------------------------------
--  파일이 생성됨 - 화요일-10월-20-2020   
--------------------------------------------------------
DROP SEQUENCE "SYS_UPI"."CONTROL_NUM";
DROP SEQUENCE "SYS_UPI"."GRADE_NUM";
DROP SEQUENCE "SYS_UPI"."INDICATORS_NUM";
DROP SEQUENCE "SYS_UPI"."RECORD_NUM";
DROP TABLE "SYS_UPI"."GRADE_TB";
DROP TABLE "SYS_UPI"."INDICATORS_TB";
DROP TABLE "SYS_UPI"."RECORD_TB";
DROP TABLE "SYS_UPI"."USER_TB";
--------------------------------------------------------
--  DDL for Sequence CONTROL_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "SYS_UPI"."CONTROL_NUM"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 64 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GRADE_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "SYS_UPI"."GRADE_NUM"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INDICATORS_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "SYS_UPI"."INDICATORS_NUM"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 63 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RECORD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "SYS_UPI"."RECORD_NUM"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 155 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table GRADE_TB
--------------------------------------------------------

  CREATE TABLE "SYS_UPI"."GRADE_TB" 
   (	"GRADE_NUM" NUMBER(10,0), 
	"A_GRADE" NUMBER(3,0), 
	"B_GRADE" NUMBER(3,0), 
	"D_GRADE" NUMBER(3,0), 
	"A_MEASURE" VARCHAR2(50 BYTE), 
	"B_MEASURE" VARCHAR2(50 BYTE), 
	"D_MEASURE" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(10 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"ACTION_CODE" NUMBER(1,0), 
	"RECORD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."GRADE_NUM" IS '등급번호PK';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."A_GRADE" IS 'A등급';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."B_GRADE" IS 'B등급';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."D_GRADE" IS 'D등급';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."A_MEASURE" IS '
A등급 조치';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."B_MEASURE" IS 'B등급 조치';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."D_MEASURE" IS 'D등급 조치';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."USER_NAME" IS '유저이름';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."ACTION_CODE" IS '행위코드';
   COMMENT ON COLUMN "SYS_UPI"."GRADE_TB"."RECORD_DATE" IS '기록날짜';
--------------------------------------------------------
--  DDL for Table INDICATORS_TB
--------------------------------------------------------

  CREATE TABLE "SYS_UPI"."INDICATORS_TB" 
   (	"CONTROL_NUM" NUMBER(10,0), 
	"INDICATORS_NUM" NUMBER(10,0), 
	"INDICATORS_NAME" VARCHAR2(100 BYTE), 
	"IS_BEST" NUMBER(1,0), 
	"IS_AGENCY" NUMBER(1,0), 
	"IS_AHA" NUMBER(1,0), 
	"IS_LINC" NUMBER(1,0), 
	"IS_TYPE3" NUMBER(1,0), 
	"ELEMENTS" VARCHAR2(200 BYTE), 
	"COL_METHOD" VARCHAR2(50 BYTE), 
	"EVAL_METHOD" VARCHAR2(8 BYTE), 
	"EVAL_STANDARD" VARCHAR2(50 BYTE), 
	"DIVISION_NAME" VARCHAR2(50 BYTE), 
	"TARGET_VAL" VARCHAR2(20 BYTE), 
	"FORMULA" VARCHAR2(200 BYTE), 
	"IS_NEGATIVE" NUMBER(1,0), 
	"IS_USE" NUMBER(1,0) DEFAULT 0, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"ACTION_CODE" NUMBER(1,0), 
	"RECORD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."CONTROL_NUM" IS '지표번호';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."INDICATORS_NUM" IS '관리번호    PK';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."INDICATORS_NAME" IS '성과지표명';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_BEST" IS '대학중장기발전계획 BEST지표';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_AGENCY" IS '기간평가 인증';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_AHA" IS '혁신지원 AHA';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_LINC" IS '사회맞춤형 LINC+   ';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_TYPE3" IS '3유형';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."ELEMENTS" IS '요소이름 구분자 사용 ex) 취업자,취업대상자';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."COL_METHOD" IS '수집방법';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."EVAL_METHOD" IS '평가방법';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."EVAL_STANDARD" IS '평가기준 ';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."DIVISION_NAME" IS '관리부서 명';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."TARGET_VAL" IS '목표값';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."FORMULA" IS '산출 식';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_NEGATIVE" IS '등급기준
';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."IS_USE" IS '사용여부(0-사용, 1-미사용)';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."USER_ID" IS '유저 아이디';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."USER_NAME" IS '유저 이름';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."ACTION_CODE" IS '행위 코드';
   COMMENT ON COLUMN "SYS_UPI"."INDICATORS_TB"."RECORD_DATE" IS '기록 날짜';
--------------------------------------------------------
--  DDL for Table RECORD_TB
--------------------------------------------------------

  CREATE TABLE "SYS_UPI"."RECORD_TB" 
   (	"RECORD_NUM" NUMBER(10,0), 
	"INDICATORS_NUM" NUMBER(10,0), 
	"INDICATORS_NAME" VARCHAR2(100 BYTE), 
	"IS_BEST" NUMBER(1,0), 
	"IS_AGENCY" NUMBER(1,0), 
	"IS_AHA" NUMBER(1,0), 
	"IS_LINC" NUMBER(1,0), 
	"IS_TYPE3" NUMBER(1,0), 
	"TARGET_VAL" VARCHAR2(20 BYTE), 
	"PRESENT_VAL" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(3 BYTE), 
	"ACHIEVE_VAL" NUMBER(6,0), 
	"USER_ID" VARCHAR2(10 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"ACTION_CODE" NUMBER(1,0), 
	"RECORD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."RECORD_NUM" IS '기록 번호';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."INDICATORS_NUM" IS '관리번호(지표번호)';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."INDICATORS_NAME" IS '성과지표명 		';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."IS_BEST" IS '대학중장기발전계획 BEST지표';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."IS_AGENCY" IS '기간평가 인증
';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."IS_AHA" IS '현식지원 AHA
';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."IS_LINC" IS '사회맞춤형 LINC+';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."IS_TYPE3" IS '3유형';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."TARGET_VAL" IS '목표 값';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."PRESENT_VAL" IS '현재 값';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."GRADE" IS '등급';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."ACHIEVE_VAL" IS '달성도';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."USER_NAME" IS '유저이름';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."ACTION_CODE" IS '행위코드';
   COMMENT ON COLUMN "SYS_UPI"."RECORD_TB"."RECORD_DATE" IS '기준일';
--------------------------------------------------------
--  DDL for Table USER_TB
--------------------------------------------------------

  CREATE TABLE "SYS_UPI"."USER_TB" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(100 BYTE), 
	"USER_GRANT" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYS_UPI"."USER_TB"."USER_ID" IS '유저 아이디';
   COMMENT ON COLUMN "SYS_UPI"."USER_TB"."USER_NAME" IS '유저 이름';
   COMMENT ON COLUMN "SYS_UPI"."USER_TB"."USER_PW" IS '유저 비밀번호';
   COMMENT ON COLUMN "SYS_UPI"."USER_TB"."USER_GRANT" IS '유저 권한 (0~2)';
REM INSERTING into SYS_UPI.GRADE_TB
SET DEFINE OFF;
Insert into SYS_UPI.GRADE_TB (GRADE_NUM,A_GRADE,B_GRADE,D_GRADE,A_MEASURE,B_MEASURE,D_MEASURE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (1,100,70,70,'차년도 달성값 이상 유지','문제점/개선사항 마련','목표 값 검토 및 문제/개선사항','9703007','관리자 ',1,to_date('20/07/25','RR/MM/DD'));
REM INSERTING into SYS_UPI.INDICATORS_TB
SET DEFINE OFF;
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (38,38,'BlueWing 프로젝트지수',1,0,0,0,0,'프로그램 참여자 수,재학생 수,프로그램','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','27.8','((프로그램 참여자 수/재학생 수) *0.5)+(프로그램*0.5)',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (42,42,'웰매칭강화지수',0,0,1,0,0,'웰매칭 산업체확보율,웰매칭 취업률,취업 프로그램 참여지수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','121.2','웰매칭 산업체확보율+웰매칭 취업률+취업 프로그램 참여지수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (43,43,'동반성자지수',0,0,1,0,0,'창의융합 인증률,재능기부봉사 참여율','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','115.6','(창의융합 인증률*0.5)+(재능기부봉사 참여율*0.5)',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (45,45,'(사회맞춤형)채용약정학생인원수',0,0,0,1,0,'채용약정학생 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','145','채용약정학생 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (46,46,'(사회맞춤형)참여학생만족도',0,0,0,1,0,'만족도 항목의 수준평가','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','84.3','만족도 항목의 수준평가',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (47,47,'(사회맞춤형)참여기업교육만족도',0,0,0,1,0,'만족도 항목의 수준평가','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','85.9','만족도 항목의 수준평가',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (50,50,'직원인건비율',0,1,0,0,0,'직원 인건비,등록금 수입','정보공시','정량','중장기발전계획 목표 측정값','행정지원처','11.00','(직원 인건비/등록금 수입)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (51,51,'학생1인당실험실습비',0,1,0,0,0,'실험실습비,재학생 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','157.100','실험실습비/재학생 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (1,1,'취업률',1,1,1,0,0,'취업자,취업대상자','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','75.60','(취업자/취업대상자)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (4,4,'재학생충원율',1,1,1,0,0,'정원내 재학생 수,편제정원','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','93.90','(정원내 재학생 수/편제정원)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (5,5,'중도탈락률',1,1,0,0,0,'제적학생 수,재적학생 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','5.20','(제적학생 수/재적학생 수)*100',1,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (7,7,'교육비환원율',1,1,1,0,0,'총교육비,등록금수입','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','172.00','(총교육비/등록금수입)*100 ',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (8,8,'입시경쟁률',1,0,0,0,0,'지원인원,모집정원','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','11:1','지원인원/모집정원',0,0,'kyungminpeal3','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (9,9,'재학생만족도',1,1,0,0,0,'구조화된 설문지를 통한 만족도 수준평가 ','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','63.6','구조화된 설문지를 통한 만족도 수준평가 ',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (11,11,'산학협력수익률',1,1,0,0,0,'산단회계운영수익,등록금수익총계','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','11.00','(산단회계운영수익/등록금수익총계)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (12,12,'평생교육원수입률',1,1,0,0,0,'평생교육원총수입,필요경비,평생교육원총수입','정보공시','정량','중장기발전계획 목표 측정값','평생교육원','36.00','((평생교육원총수입-필요경비)/평생교육원총수입)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (15,15,'학생직무능력성취도',1,0,0,0,0,'학생이 수강한 능력단위에 대한 종합성취도','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','82.0','학생이 수강한 능력단위에 대한 종합성취도',0,0,'kyungminpeal3','관리자',1,to_date('20/07/22','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (16,16,'현장실습만족도',1,0,0,0,0,'만족도 항목(10개)의 평균','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','89.0','만족도 항목(10개)의 평균',0,0,'kyungminpeal3','관리자',1,to_date('20/07/23','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (18,18,'산업체만족도',1,1,0,0,0,'구조화된 설문지를 통한 만족도 수준평가','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','90.0','구조화된 설문지를 통한 만족도 수준평가 ',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (19,19,'복지예산집행률',1,0,0,0,0,'복지지원 지급액,달성목표액','정보공시','정량','중장기발전계획 목표 측정값','행정지원처','100.00','(복지지원 지급액/달성목표액)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (21,21,'산업체경력전임교원확보율',1,0,0,0,0,'3년 이상 산업체경력 전임교원,교원법정정원','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','17.00','(3년 이상 산업체경력 전임교원/교원법정정원)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (25,25,'NCS/직무분석기반교육여건예산집행률',1,0,0,0,0,'집행액,예산액','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','100.00','(집행액/예산액)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (37,37,'이력관리향상지수',1,0,0,0,0,'마일리지 참여자 수,재학생 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','93.00','(마일리지 참여자 수/재학생 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (48,48,'(사회맞춤형)협약산업체취업률',0,0,0,1,0,'협약산업체 취업자 수,채용약정 인원 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','60.4','(협약산업체 취업자 수/채용약정 인원 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (55,55,'주당수업시수비율',0,1,0,0,0,'전임교원 총 주당 수업시수,전임교원 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','50.00','(전임교원 총 주당 수업시수/전임교원 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (2,2,'유지취업률',0,1,0,0,0,'(1차~4차)기준일 유지 건강보험 직장가입자,조사기준년 12월31일 건강보험 직장가입자','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','72.00','(1차~4차)기준일 유지 건강보험 직장가입자/조사기준년 12월31일 건강보험 직장가입자)*100 ',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (3,3,'신입생충원율',1,1,0,0,0,'정원내 입학자 수,정원 내 모집인원','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','100.00','(정원내 입학자 수/정원 내 모집인원)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (23,23,'외부사업선정금액',1,0,0,0,0,'외부사업선정금액','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','190','외부사업선정금액',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (40,40,'역량교육강화지수',0,0,1,0,0,'학생직무능력 향상율,학생이력점수,SPEC 관리지수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','102','(학생직무능력 향상율*0.4)+(학생이력점수*0.3)+(SPEC 관리지수*0.2)',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (14,14,'교육과정만족도',1,0,0,0,0,'구조화된 설문지를 통한 만족도 수준평가','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','65.0','구조화된 설문지를 통한 만족도 수준평가',0,0,'kyungminpeal3','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (22,22,'지역사회협력지수',1,0,0,0,0,'최우수+우수회사 수,전체가족회사 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','25.00','(최우수+우수회사 수/전체가족회사 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (26,26,'NCS/직무분석기반교육과정도입률',1,0,0,0,0,'NCS도입 과목 수(전공),전체과목 수(전공)','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','90.00','(NCS도입 과목 수(전공)/전체과목 수(전공))*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (27,27,'NCS/직무분석기반 학과 CQI운영률',1,0,0,0,0,'CQI실시학과 수,전체학과 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','100.00','(CQI실시학과 수/전체학과 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (29,29,'현장실습이수자수',1,0,0,0,0,'현장실습 이수자 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','1000','현장실습 이수자 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (30,30,'교원1인당 연수시간',1,0,0,0,0,'총 연수시간,총 교원 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','32.7','총 연수시간/총 교원 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (31,31,'직원1인당 연수시간',1,0,0,0,0,'총 연수시간,총 직원 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','7','총 연수시간/총 직원 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (33,33,'학생복지서비스만족도',1,0,0,0,0,'만족도 항목(12개)의 수준평가','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','67.00','만족도 항목(12개)의 수준평가',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (34,34,'취창업프로그램운영수',1,0,0,0,0,'취창업프로그램 운영 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','25','취창업프로그램 운영 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (52,52,'전임교원1인당연구실적',0,1,0,0,0,'연구실적 건수,전임교원 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','0.20','연구실적 건수/전임교원 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (54,54,'실습과목시수비율',0,1,0,0,0,'실습과목 시수,실습과목+이론과목 시수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','47.50','((실습과목 시수/(실습과목+이론과목 시수))*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (6,6,'전임교원확보율',1,0,1,0,0,'전임교원 수,교원법정정원(재학생기준)','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','57.76','(전임교원 수/교원법정정원(재학생기준))*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (10,10,'교직원만족도',1,1,0,0,0,'구조화된 설문지를 통한 만족도 수준평가 ','정보공시','정량','중장기발전계획 목표 측정값','대학발전운영실','53.3','구조화된 설문지를 통한 만족도 수준평가 ',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (13,13,'창업교육지수',1,0,0,0,0,'창업강좌개설비율,창업강좌 이수율','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','15.0','(창업강좌개설비율*0.5)+(창업강좌 이수율*0.5)',0,0,'kyungminpeal3','관리자',1,to_date('20/07/20','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (17,17,'장학금지급률',1,1,0,0,0,'교내장학금,교외장학금,등록금수입 총액','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','16.50','(교내장학금+교외장학금)/등록금수입 총액*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/24','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (20,20,'지자체협력건수',1,0,0,0,0,'가족회사 실적,가족회사 목표','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','9','(가족회사 실적/가족회사 목표) *100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (24,24,'캡스톤디자인이수율',1,0,0,0,0,'이수학생 수,전체 재학생 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','24.00','(이수학생 수/전체 재학생 수) *100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/25','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (28,28,'사회맞춤형 교육과정 이수 졸업자수',1,0,0,0,0,'사회맞춤형 교육과정 이수졸업자 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','120','사회맞춤형 교육과정 이수졸업자 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (32,32,'입시홍보기여지수',1,0,0,0,0,'박람회참여건수,고교대상홍보건수,온라인홍보건수','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','14.5','(박람회참여건수*0.5)+(고교대상홍보건수*0.2)+(온라인홍보건수*0.3)',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (39,39,'총강좌수',0,0,1,0,0,'해당학기 총 강좌 수,해당연도 재학생 수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','26.97','(해당학기 총 강좌 수/해당연도 재학생 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (41,41,'교육품질개선지수',0,0,1,0,0,'소규모 강좌비율,웰매칭 취업률,취업 프로그램 참여율','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','107.3','(소규모 강좌비율*0.3)+(유연한 학사제도 적용률*0.4)+(이러닝 운영지수*0.3)',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (44,44,'(사회맞춤형)참여학생수',0,0,0,1,0,'사회맞춤형 프로그램 참여자 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','189','사회맞춤형 프로그램 참여자 수',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (49,49,'교원인건비비율',0,1,0,0,0,'교원 인건비,등록금 수입','정보공시','정량','중장기발전계획 목표 측정값','행정지원처','30.00','(교원 인건비/등록금 수입)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (53,53,'성적분포비율',0,1,0,0,0,'점수 구간별 성적인정 학생 수,과목별 성적인정 학생 총수','정보공시','정량','중장기발전계획 목표 측정값','교무학생처','40.0','(점수 구간별 성적인정 학생 수/과목별 성적인정 학생 총수)*100',1,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (35,35,'취업교과참여지수',1,0,0,0,0,'취업교과목 이수학생 수,재학생 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','91.50','(취업교과목 이수학생 수/재학생 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (36,36,'창업교과참여지수',1,0,0,0,0,'창업교과목 이수학생 수,재학생 수','정보공시','정량','중장기발전계획 목표 측정값','산학협력처','47.00','(창업교과목 이수학생 수/재학생 수)*100',0,0,'kyungminpeal3','관리자',1,to_date('20/07/26','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (56,56,'교육과정 운영비율',0,0,0,0,1,'실제 운영 직업교육과정 수,개설 계획 직업교육과정 수','정보공시','정량','목표 측정값','입학취업처','72.2','(실제 운영 직업교육과정 수/개설 계획 직업교육과정 수)*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (57,57,'모집대비 실 참여 교육생 비율',0,0,0,0,1,'직업교육과정 참여학생 수,직업교육과정 모집학생 수','정보공시','정량','목표 측정값','입학취업처','87.9','(직업교육과정 참여학생 수/직업교육과정 모집학생 수)*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (58,58,'교육과정 이수율',0,0,0,0,1,'직업교육과정 이수학생 수,직업교육과정 참여학생 수','정보공시','정량','목표 측정값','입학취업처','98.2','(직업교육과정 이수학생 수/직업교육과정 참여학생 수)*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (59,59,'교육품질개선지수',0,0,0,0,1,'교과목 CQI 적용률,현장수업 강좌율','정보공시','정량','목표 측정값','입학취업처','104.5','((교과목 CQI 적용률*0.4)+(교과목 CQI 적용률*0.3)+(현장수업 강좌율*0.3)*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (60,60,'후진학 모델 활성화지수',0,0,0,0,1,'원격수업 이수율,유연한 학사제도 도입율,학점누적제 적용 학생 수','정보공시','정량','목표 측정값','입학취업처','101.7','((원격수업 이수율*0.3)+(유연한 학사제도 도입율*0.3)+(학점누적제 적용 학생 수*0.3))*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (61,61,'평생직업교육 운영 지수',0,0,0,0,1,'수강생 상담률,취창업정보 제공률,전임교원 강의 참여율','정보공시','정량','목표 측정값','입학취업처','100','((수강생 상담률*0.3)+(취창업정보 제공률*0.3)+(전임교원 강의 참여율*0.4))*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (62,62,'산관학 거버넌스 협력지수',0,0,0,0,1,'거버넌스 회의참여율,지역수요조사연계 프로그램 개발률,거버넌스 신규협약률','정보공시','정량','목표 측정값','입학취업처','205.3','((거버넌스 회의참여율*0.4)+(지역수요조사연계 프로그램 개발률*0.3)+(거버넌스 신규협약률*0.3))*100',0,0,'9703007','관리자',1,to_date('20/09/01','RR/MM/DD'));
Insert into SYS_UPI.INDICATORS_TB (CONTROL_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,ELEMENTS,COL_METHOD,EVAL_METHOD,EVAL_STANDARD,DIVISION_NAME,TARGET_VAL,FORMULA,IS_NEGATIVE,IS_USE,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (63,1,'취업률',1,1,1,0,0,'취업자,취업대상자','정보공시','정량','중장기발전계획 목표 측정값','입학취업처','75.60','(취업자/취업대상자)*100',0,0,'9703007','관리자',1,to_date('20/09/11','RR/MM/DD'));
REM INSERTING into SYS_UPI.RECORD_TB
SET DEFINE OFF;
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (37,37,'이력관리향상지수',1,0,0,0,0,'91.7 ','91.7 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (38,38,'BlueWing 프로젝트지수',1,0,0,0,0,'23.0 ','26.6 ','A',116,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (39,39,'총 강좌수',1,0,0,0,0,'28.33 ','33.86 ','A',120,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (40,49,'교원인건비비율',0,0,1,0,0,'30.0 ','38.4 ','A',128,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (41,50,'직원인건비비율',0,0,1,0,0,'11.0 ','16.64 ','A',151,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (42,51,'학생1인당실험실습비',0,0,0,1,0,'157.1 ','189.2 ','A',120,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (43,52,'전임교원1인당연구실적',0,0,0,1,0,'0.2 ','0.27 ','A',135,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (44,53,'성적분포비율',0,0,0,1,0,'40.0','29.4','A',136,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (45,54,'실습과목시수비율',0,0,0,1,0,'47.5 ','46.1 ','B',97,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (46,55,'주당수업시수비율',0,0,0,1,0,'50.0 ','50.5 ','A',101,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (47,1,'취업률',1,1,1,0,1,'72.5 ','68.9 ','B',95,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (48,2,'유지취업률',0,1,0,0,0,'70.0 ','73.9 ','A',106,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (49,3,'신입생충원율',0,1,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (50,4,'재학생충원율',0,1,0,0,0,'93.7 ','92.8 ','B',99,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (51,5,'중도탈락률',0,1,0,0,0,'5.3 ','7.2 ','B',74,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (52,6,'전임교원확보율',0,1,0,0,0,'57.76 ','64.00 ','A',111,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (64,18,'산업체만족도',1,1,0,0,0,'84.5 ','90.0 ','A',107,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (65,19,'복지예산 집행률',1,1,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (66,20,'지자체협력 건 수',1,0,0,0,0,'9','9','A',100,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (67,21,'산업체경력전임교원확보율',1,0,0,0,0,'16.0 ','17.0 ','A',106,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (68,22,'지역사회협력지수',1,0,0,0,0,'23.0 ','25.0 ','A',109,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (69,23,'외부사업선정금액',1,0,0,0,0,'180','198.3','A',110,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (70,24,'캡스톤디자인이수율',1,1,0,0,0,'22.0 ','25.0 ','A',114,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (71,25,'NCS/직무분석기반 교육여건 예산 집행률',1,1,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (72,26,'NCS/직무분석기반 교육과정 도입률',1,0,0,0,0,'90.0 ','88.4 ','B',98,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (73,27,'NCS/직무분석기반 학과 CQI운영률',1,0,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (74,28,'사회맞춤형 교육과정 이수졸업자 수',1,0,0,0,0,'100','120','A',120,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (75,29,'현장실습이수자수',1,0,0,0,0,'1050','1000','B',95,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (76,30,'교원1인당 연수시간',1,0,0,0,0,'32.6 ','30.1 ','B',92,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (63,17,'장학금지급률',1,1,0,0,0,'16.5 ','16.0 ','B',97,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (83,37,'이력관리향상지수',1,0,0,0,0,'93.0 ','92.2 ','B',99,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (84,38,'BlueWing 프로젝트지수',1,0,0,0,0,'25.3 ','27.1 ','A',107,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (85,39,'총 강좌수',1,0,0,0,0,'28.32 ','33.32 ','A',118,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (86,49,'교원인건비비율',0,0,1,0,0,'30.0 ','40.50 ','A',135,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (87,50,'직원인건비비율',0,0,1,0,0,'11.0 ','19.10 ','A',174,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (88,51,'학생1인당실험실습비',0,0,0,1,0,'157.1 ','169.5 ','A',108,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (89,52,'전임교원1인당연구실적',0,0,0,1,0,'0.2 ','0.32 ','A',160,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (90,53,'성적분포비율',0,0,0,1,0,'40.0','29.1 ','A',136,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (91,54,'실습과목시수비율',0,0,0,1,0,'47.5 ','47.0 ','B',99,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (92,55,'주당수업시수비율',0,0,0,1,0,'50.0 ','48.6 ','B',97,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (77,31,'직원1인당 연수시간',1,0,0,0,0,'6.0 ','21.0 ','A',350,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (2,2,'유지취업률',0,1,0,0,0,'68.4 ','68.4 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (3,3,'신입생충원율',0,1,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (4,4,'재학생충원율',0,1,0,0,0,'93.5 ','93.7 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (5,5,'중도탈락률',0,1,0,0,0,'5.3 ','5.5 ','B',96,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (6,6,'전임교원확보율',0,1,0,0,0,'57.76 ','61.72 ','A',107,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (7,7,'교육비환원율',0,1,0,0,0,'152.0 ','133.5 ','B',88,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (8,8,'입시경쟁률',0,1,0,0,0,'10:1','9.6:1','B',96,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (9,9,'재학생만족도',1,0,0,0,1,'65.6 ','62.1 ','B',95,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (10,10,'교직원만족도',1,1,0,0,0,'58.4 ','59.6 ','A',102,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (11,11,'산학협력수익률',1,1,1,0,1,'9.0 ','11.1 ','A',123,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (12,12,'평생교육원수익률',1,1,0,0,1,'36.0 ','26.5 ','B',74,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (13,13,'창업교육지수',1,0,1,0,0,'13.0 ','21.0 ','A',162,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (14,14,'교육과정만족도',1,1,1,0,0,'64.0 ','60.9 ','B',95,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (15,15,'학생직무능력성취도',1,0,0,0,1,'80.0 ','78.4 ','B',98,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (16,16,'현장실습만족도',1,1,0,0,0,'88.0 ','86.9 ','B',99,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (17,17,'장학금지급률',1,1,0,0,0,'16.5 ','16.6 ','A',101,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (18,18,'산업체만족도',1,1,0,0,0,'82.9 ','84.5 ','A',102,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (19,19,'복지예산 집행률',1,1,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (20,20,'지자체협력 건 수',1,0,0,0,0,'8','9','A',113,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (21,21,'산업체경력전임교원확보율',1,0,0,0,0,'15.0 ','15.0 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (22,22,'지역사회협력지수',1,0,0,0,0,'20.0 ','27.9 ','A',140,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (23,23,'외부사업선정금액',1,0,0,0,0,'170','160.1 ','B',94,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (24,24,'캡스톤디자인이수율',1,1,0,0,0,'20.0 ','25.8 ','A',129,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (25,25,'NCS/직무분석기반 교육여건 예산 집행률',1,1,0,0,0,'100.0 ','95.0 ','B',95,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (26,26,'NCS/직무분석기반 교육과정 도입률',1,0,0,0,0,'90.0 ','92.1 ','A',102,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (27,27,'NCS/직무분석기반 학과 CQI운영률',1,0,0,0,0,'100.0 ','100.0 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (28,28,'사회맞춤형 교육과정 이수졸업자 수',1,0,0,0,0,'100','118','A',118,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (29,29,'현장실습이수자수',1,0,0,0,0,'1100','1052','B',96,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (30,30,'교원1인당 연수시간',1,0,0,0,0,'32.5 ','34.4 ','A',106,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (31,31,'직원1인당 연수시간',1,0,0,0,0,'5.0 ','26.0 ','A',520,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (32,32,'입시홍보기여지수',1,0,0,0,0,'12.0 ','13.2 ','A',110,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (33,33,'학생복지서비스만족도',1,0,0,0,0,'60.0 ','64.7 ','A',108,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (34,34,'취?창업프로그램운영수',1,0,0,0,0,'23 ','23 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (35,35,'취업교과참여지수',1,0,0,0,0,'90.3 ','90.3 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (36,36,'창업교과참여지수',1,0,0,0,0,'46.7 ','37.9 ','B',81,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (53,7,'교육비환원율',0,1,0,0,0,'162.0 ','135.0 ','B',83,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (54,8,'입시경쟁률',0,1,0,0,0,'10:1','10.7:1','A',107,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (55,9,'재학생만족도',1,0,0,0,1,'62.1 ','63.6 ','A',102,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (56,10,'교직원만족도',1,1,0,0,0,'59.6 ','53.3 ','B',89,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (57,11,'산학협력수익률',1,1,1,0,1,'10.0 ','8.0 ','B',80,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (58,12,'평생교육원수익률',1,1,0,0,1,'36.0 ','26.5 ','B',74,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (59,13,'창업교육지수',1,0,1,0,0,'15.0 ','13.8 ','B',92,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (60,14,'교육과정만족도',1,1,1,0,0,'64.0 ','60.5 ','B',95,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (1,1,'취업률',1,1,1,0,1,'69.2 ','69.2 ','A',100,'9703007','관리자',1,to_date('17/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (78,32,'입시홍보기여지수',1,0,0,0,0,'13.2 ','13.2 ','A',100,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (79,33,'학생복지서비스만족도',1,0,0,0,0,'65.0 ','65.6 ','A',101,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (80,34,'취?창업프로그램운영수',1,0,0,0,0,'25 ','27 ','A',108,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (81,35,'취업교과참여지수',1,0,0,0,0,'91.0 ','88.0 ','B',97,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (82,36,'창업교과참여지수',1,0,0,0,0,'47.0 ','23.3 ','D',50,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (61,15,'학생직무능력성취도',1,0,0,0,1,'82.0 ','78.4 ','B',96,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (62,16,'현장실습만족도',1,1,0,0,0,'88.5 ','85.5 ','B',97,'9703007','관리자',1,to_date('18/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (154,62,'산관학 거버넌스 협력지수',0,0,0,0,1,'205.3 ','60.0 ','D',29,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (93,1,'취업률',1,1,1,0,1,'75.6','67.9','B',90,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (94,2,'유지취업률',0,1,0,0,0,'72','72.21','A',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (95,3,'신입생충원율',0,1,0,0,0,'100','100','A',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (96,4,'재학생충원율',0,1,0,0,0,'93.9','93.3','B',99,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (97,5,'중도탈락률',0,1,0,0,0,'5.2','5.78','B',90,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (98,6,'전임교원확보율',0,1,0,0,0,'57.76','62.07','A',107,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (99,7,'교육비환원율',0,1,0,0,0,'172','130','B',76,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (100,8,'입시경쟁률',0,1,0,0,0,'11:1','8.83:1','B',80,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (101,9,'재학생만족도',1,0,0,0,1,'63.6','63.7','A',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (102,10,'교직원만족도',1,1,0,0,0,'53.3','57.2','A',107,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (103,11,'산학협력수익률',1,1,1,0,1,'11','7','D',64,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (104,12,'평생교육원수익률',1,1,0,0,1,'36','76.21','A',212,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (105,13,'창업교육지수',1,0,1,0,0,'15','16.7','A',111,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (106,14,'교육과정만족도',1,1,1,0,0,'65','60.8','B',94,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (107,15,'학생직무능력성취도',1,0,0,0,1,'82','78.6','B',96,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (108,16,'현장실습만족도',1,1,0,0,0,'89','82.9','B',93,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (109,17,'장학금지급률',1,1,0,0,0,'16.5','15.74','B',95,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (110,18,'산업체만족도',1,1,0,0,0,'90.0 ','81.8','B',91,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (111,19,'복지예산 집행률',1,1,0,0,0,'100','95','B',95,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (112,20,'지자체협력 건 수',1,0,0,0,0,'9','8','B',89,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (113,21,'산업체경력전임교원확보율',1,0,0,0,0,'17','17.4','A',102,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (114,22,'지역사회협력지수',1,0,0,0,0,'25','24.4','B',98,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (115,23,'외부사업선정금액',1,0,0,0,0,'190','282.7','A',149,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (116,24,'캡스톤디자인이수율',1,1,0,0,0,'24','30.61','A',128,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (117,25,'NCS/직무분석기반 교육여건 예산 집행률',1,1,0,0,0,'100','99.9','B',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (118,26,'NCS/직무분석기반 교육과정 도입률',1,0,0,0,0,'90','86.8','B',96,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (119,27,'NCS/직무분석기반 학과 CQI운영률',1,0,0,0,0,'100','100','A',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (120,28,'사회맞춤형 교육과정 이수졸업자 수',1,0,0,0,0,'120','101','B',84,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (121,29,'현장실습이수자수',1,0,0,0,0,'1000','339','D',34,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (122,30,'교원1인당 연수시간',1,0,0,0,0,'32.7','9.4','D',29,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (123,31,'직원1인당 연수시간',1,0,0,0,0,'7','15.3','A',219,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (124,32,'입시홍보기여지수',1,0,0,0,0,'14.5','22.3','A',154,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (125,33,'학생복지서비스만족도',1,0,0,0,0,'67','65.8','B',98,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (126,34,'취?창업프로그램운영수',1,0,0,0,0,'25','32','A',128,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (127,35,'취업교과참여지수',1,0,0,0,0,'91.5','32.27','D',35,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (128,36,'창업교과참여지수',1,0,0,0,0,'47','30.9','D',66,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (129,37,'이력관리향상지수',1,0,0,0,0,'93','97.55','A',105,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (130,38,'BlueWing 프로젝트지수',1,0,0,0,0,'27.8','19.5','B',70,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (131,39,'총 강좌수',1,0,0,0,0,'26.96','32.46','A',120,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (132,40,'역량교육강화지수',0,0,1,0,0,'102','116.3','A',114,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (133,41,'교육품질개선지수',0,0,1,0,0,'107.3','156.8','A',146,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (134,42,'웰매칭강화지수',0,0,1,0,0,'121.2','143.8','A',119,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (135,43,'동반성장지수',0,0,1,0,0,'115.6','100.5','B',87,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (136,44,'사회맞춤형참여학생수',0,0,0,1,0,'189','183','B',97,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (137,45,'채용약정학생인원수',0,0,0,1,0,'145','145','A',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (138,46,'참여학생만족도',0,0,0,1,0,'84.3','84.7','A',100,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (139,47,'참여기업교육만족도',0,0,0,1,0,'85.9','84.7','B',99,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (140,48,'협약산업체취업률',0,0,0,1,0,'60.4','56.7','B',94,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (141,49,'교원인건비비율',0,0,1,0,0,'30.0 ','41.96','A',140,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (142,50,'직원인건비비율',0,0,1,0,0,'11.0 ','19.42','A',177,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (143,51,'학생1인당실험실습비',0,0,0,1,0,'157.1','211.244','A',134,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (144,52,'전임교원1인당연구실적',0,0,0,1,0,'0.2','0.24','A',120,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (145,53,'성적분포비율',0,0,0,1,0,'40.0','29.9','A',136,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (146,54,'실습과목시수비율',0,0,0,1,0,'47.5','50.92','A',107,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (147,55,'주당수업시수비율',0,0,0,1,0,'50.0 ','53.6','A',107,'9703007','관리자',1,to_date('19/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (148,56,'교육과정 운영비율',0,0,0,0,1,'72.2 ','66.0 ','B',91,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (149,57,'모집대비 실 참여 교육생 비율',0,0,0,0,1,'87.9 ','82.7 ','B',94,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (150,58,'교육과정 이수율',0,0,0,0,1,'98.2 ','97.7 ','B',99,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (151,59,'교육품질개선지수',0,0,0,0,1,'104.5 ','30.0 ','D',29,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (152,60,'후진학 모델 활성화지수',0,0,0,0,1,'101.7 ','30.0 ','D',29,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
Insert into SYS_UPI.RECORD_TB (RECORD_NUM,INDICATORS_NUM,INDICATORS_NAME,IS_BEST,IS_AGENCY,IS_AHA,IS_LINC,IS_TYPE3,TARGET_VAL,PRESENT_VAL,GRADE,ACHIEVE_VAL,USER_ID,USER_NAME,ACTION_CODE,RECORD_DATE) values (153,61,'평생직업교육 운영 지수',0,0,0,0,1,'100.0 ','0.0 ','D',0,'9703007','관리자',1,to_date('20/07/21','RR/MM/DD'));
REM INSERTING into SYS_UPI.USER_TB
SET DEFINE OFF;
Insert into SYS_UPI.USER_TB (USER_ID,USER_NAME,USER_PW,USER_GRANT) values ('9703007','관리자','63531706e153dbcf1b599171eea3be0efae864e97fbf3f102b1e328641c18ac1',3);
Insert into SYS_UPI.USER_TB (USER_ID,USER_NAME,USER_PW,USER_GRANT) values ('20203301','곽지용','d8f01284fda46e5584a444a23ea4d977b89b1ebb586812b3cad97662270e4aed',0);
Insert into SYS_UPI.USER_TB (USER_ID,USER_NAME,USER_PW,USER_GRANT) values ('17831004','관리자2','d8f01284fda46e5584a444a23ea4d977b89b1ebb586812b3cad97662270e4aed',1);
--------------------------------------------------------
--  DDL for Index GRADE_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_UPI"."GRADE_TB_PK" ON "SYS_UPI"."GRADE_TB" ("GRADE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INDICATORS_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_UPI"."INDICATORS_TB_PK" ON "SYS_UPI"."INDICATORS_TB" ("CONTROL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECORD_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_UPI"."RECORD_TB_PK" ON "SYS_UPI"."RECORD_TB" ("RECORD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_UPI"."USER_TB_PK" ON "SYS_UPI"."USER_TB" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GRADE_TB
--------------------------------------------------------

  ALTER TABLE "SYS_UPI"."GRADE_TB" ADD CONSTRAINT "GRADE_TB_PK" PRIMARY KEY ("GRADE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("D_GRADE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("B_GRADE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("A_GRADE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("A_MEASURE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("GRADE_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("D_MEASURE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("B_MEASURE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."GRADE_TB" MODIFY ("RECORD_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INDICATORS_TB
--------------------------------------------------------

  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("INDICATORS_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("INDICATORS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_BEST" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_AGENCY" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_AHA" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_LINC" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_TYPE3" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("ELEMENTS" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("COL_METHOD" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("EVAL_METHOD" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("EVAL_STANDARD" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("DIVISION_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("TARGET_VAL" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_NEGATIVE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("IS_USE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("CONTROL_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" ADD CONSTRAINT "INDICATORS_TB_PK" PRIMARY KEY ("CONTROL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."INDICATORS_TB" MODIFY ("RECORD_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECORD_TB
--------------------------------------------------------

  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("IS_BEST" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("IS_AGENCY" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("IS_AHA" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("IS_LINC" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("IS_TYPE3" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("TARGET_VAL" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("PRESENT_VAL" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("ACHIEVE_VAL" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("RECORD_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("RECORD_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("INDICATORS_NUM" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("INDICATORS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" ADD CONSTRAINT "RECORD_TB_PK" PRIMARY KEY ("RECORD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."RECORD_TB" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_TB
--------------------------------------------------------

  ALTER TABLE "SYS_UPI"."USER_TB" MODIFY ("USER_GRANT" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."USER_TB" ADD CONSTRAINT "USER_TB_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS_UPI"."USER_TB" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."USER_TB" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS_UPI"."USER_TB" MODIFY ("USER_ID" NOT NULL ENABLE);
